call plug#begin()
    Plug 'neoclide/coc.nvim'
    Plug 'kaicataldo/material.vim'
    Plug 'tomtom/tcomment_vim'
    Plug 'vim-airline/vim-airline'
	Plug 'mattn/emmet-vim'
	Plug 'ctrlpvim/ctrlp.vim'
	Plug 'tpope/vim-abolish'
	Plug 'tpope/vim-surround'
	Plug 'preservim/nerdtree'
call plug#end()
